apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: celery
  name: celery-controller
spec:
  selector:
    matchLabels:
      app: taskQueue
      component: celery  
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: celery
    spec:
      containers:
      - image: endocode/celery-app-add
        name: celery
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
            
    