apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: celery
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50